# Generated by Django 4.2.7 on 2026-03-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_invoice_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.AlterModelOptions(
            name='passwordresetrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Password Reset Request', 'verbose_name_plural': 'Password Reset Requests'},
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='passwordresetrequest',
            table=None,
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
