# Generated by Django 4.2.7 on 2026-03-28 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_invoiceitem_invoice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("forecast", "Demand Forecast"),
                            ("anomaly", "Anomaly Detection"),
                            ("recommendation", "Recommendation"),
                            ("prediction", "Prediction"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("impact", models.CharField(blank=True, max_length=200)),
                ("confidence_score", models.IntegerField(default=80)),
                ("is_actioned", models.BooleanField(default=False)),
                ("actioned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actioned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_insights",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["insight_type", "priority"],
                        name="ai_insights_insight_ffa2c3_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="ai_insights_created_a5bbff_idx"
                    ),
                ],
            },
        ),
    ]
